-- 1. Création de la base
CREATE DATABASE IF NOT EXISTS mobilemoney_db;
USE mobilemoney_db;

-- 2. Table CLIENT
CREATE TABLE IF NOT EXISTS CLIENT (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    telephone VARCHAR(15) UNIQUE NOT NULL,
    adresse VARCHAR(100)
);

-- 3. Table COMPTE
CREATE TABLE IF NOT EXISTS COMPTE (
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero_compte VARCHAR(20) UNIQUE NOT NULL,
    solde DOUBLE DEFAULT 0.0,
    client_id INT NOT NULL,
    CONSTRAINT fk_client FOREIGN KEY (client_id) REFERENCES CLIENT(id) ON DELETE CASCADE
);

-- 4. Table OPERATIONS
CREATE TABLE IF NOT EXISTS OPERATIONS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    type_operation ENUM('DEPOT', 'RETRAIT', 'TRANSFERT', 'PAIEMENT') NOT NULL,
    montant DOUBLE NOT NULL,
    date_operation DATETIME DEFAULT CURRENT_TIMESTAMP,
    compte_id INT NOT NULL,
    marchand VARCHAR(50),
    CONSTRAINT fk_compte FOREIGN KEY (compte_id) REFERENCES COMPTE(id) ON DELETE CASCADE
);

--Ajout des colonnes pour les opérations de transfert
ALTER TABLE OPERATIONS ADD COLUMN compte_source INT;
ALTER TABLE OPERATIONS ADD COLUMN compte_destination INT;
ALTER TABLE OPERATIONS DROP FOREIGN KEY fk_compte;
ALTER TABLE OPERATIONS DROP COLUMN compte_id;
ALTER TABLE OPERATIONS ADD CONSTRAINT fk_source FOREIGN KEY (compte_source) REFERENCES COMPTE(id);
ALTER TABLE OPERATIONS ADD CONSTRAINT fk_destination FOREIGN KEY (compte_destination) REFERENCES COMPTE(id);